# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-24 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov1', '0002_auto_20170822_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='birth',
            name='form_no',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birth',
            name='id_number',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birth',
            name='number',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.IntegerField(max_length=100),
        ),
    ]
