# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-25 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov1', '0003_auto_20170825_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death',
            name='dmonth',
        ),
        migrations.RemoveField(
            model_name='death',
            name='dyear',
        ),
        migrations.RemoveField(
            model_name='death',
            name='place',
        ),
    ]
